import vdbRedirect from './product/vdb-redirect';
import bangleRedirect from './product/bangleRedirect';
import productCarousel from './product/product-carousel';
import modalTriggers from './product/modal-triggers';
import stickyForm from './product/sticky-form';
import addToWishlist from './product/add-to-wishlist';
import klaviyoForm from './product/klaviyo-form';
import globoRecommendations from './product/globo-recommendations';
import removeUspFromHandbags from './product/remove-usp-from-handbags';
import imagePanZoom from './product/imagePanZoom';
import bangleCustomizer from './product/bangleCustomizer';
import customVariantImageSwap from './product/customVariantImageSwap';
import breadReplace from './product/bread-replacement';
import productModal from './product/product-modal';

vdbRedirect();
bangleRedirect();
productCarousel();
modalTriggers();
stickyForm();
addToWishlist();
klaviyoForm();
globoRecommendations();
removeUspFromHandbags();
imagePanZoom();
bangleCustomizer();
customVariantImageSwap();
breadReplace();
productModal();
